name: vue-work

services:
  db:
    container_name: vue-work-db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: psql
    ports:
      - 8531:5432

  backend:
    container_name: vue-work-backend
    build: ./backend
    command: npm start
    volumes:
      - ./backend:/src/backend
    depends_on:
      - db
    ports:
      - 8501:3000

  frontend:
    container_name: vue-work-frontend
    build:
      context: ./frontend
#    https://github: com/vitejs/vite/issues/2671#issuecomment-829535806:
    command: sh -c "npm rebuild esbuild && npm run dev"
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - '8581:8080'
    volumes:
      - ./frontend:/src/frontend
